# Generated by Django 4.1.5 on 2023-02-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subject_data_m1_subject_data_m10_subject_data_m2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_data',
            name='faculty',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_data',
            name='year',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
