# Generated by Django 4.1.5 on 2023-02-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subject_data_faculty_subject_data_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_data',
            name='semester',
            field=models.CharField(max_length=50),
        ),
    ]
