# Generated by Django 4.1.5 on 2023-02-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_subject_data_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_data',
            name='q0',
        ),
    ]
