# Generated by Django 4.1.5 on 2023-05-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_subject_data_q0'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_data',
            name='blooms_level',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
