# Generated by Django 4.1.5 on 2023-05-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_subject_data_blooms_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_data',
            name='blooms_level',
        ),
        migrations.AddField(
            model_name='subject_data',
            name='bl1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_data',
            name='bl10',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_data',
            name='bl2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_data',
            name='bl3',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_data',
            name='bl4',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_data',
            name='bl5',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_data',
            name='bl6',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_data',
            name='bl7',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_data',
            name='bl8',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_data',
            name='bl9',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q10',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q3',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q4',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q5',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q6',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q7',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q8',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q9',
            field=models.CharField(max_length=500),
        ),
    ]
